on:
  push:
    branches:
      - staging
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v3

      - name: ğŸ“¦ Install Pnpm
        run: npm i -g pnpm

      - name: ğŸ“¦ Install Dependencies
        run: pnpm install

      - name: ğŸ— Build SvelteKit
        run: pnpm run build

      - name: Prune
        run: pnpm prune --production

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.artcon.com.bd
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /staging.artcon.com.bd
